iris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predict.urls', namespace='predict')),

]

predict/urls.py
from django.urls import path
from . import views

app_name = "predict"

urlpatterns = [
    path('predictor/', views.predict, name='prediction_page'),
    path('predict/', views.predict_chances, name='submit_prediction'),
    path('results/', views.view_results, name='results'),
    path('about/',views.view_about,name='about'),
    path('doctor/',views.view_doctor,name='doctor'),
    path('register/', views.register_request, name='register'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name= 'logout'),
    path('', views.home_request, name= 'home'),

]

predict/models.py
from django.db import models


class PredResults(models.Model):

    Patient_ID = models.IntegerField()
    Patient_Age = models.IntegerField()
    Patient_Gender = models.IntegerField()
    Patient_Blood_Pressure = models.IntegerField()
    Patient_Heartrate = models.IntegerField()
    Heart_Disease = models.CharField(max_length=30)

    def __str__(self):
        return self.Heart_Disease

predict/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

predict/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import pandas as pd
from .models import PredResults
from .forms import NewUserForm
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout

def home_request(request):
    return render(request, 'home.html')

def predict(request):
    return render(request, 'predict.html')


def predict_chances(request):

    if request.POST.get('action') == 'post':

        # Receive data from client
        Patient_ID = int(request.POST.get('Patient_ID'))
        Patient_Age = int(request.POST.get('Patient_Age'))
        Patient_Gender = int(request.POST.get('Patient_Gender'))
        Patient_Blood_Pressure = int(request.POST.get('Patient_Blood_Pressure'))
        Patient_Heartrate = int(request.POST.get('Patient_Heartrate'))

        # Unpickle model
        model = pd.read_pickle(r"new_model.pickle")
        # Make prediction
        result = model.predict([[Patient_ID, Patient_Age, Patient_Gender, Patient_Blood_Pressure, Patient_Heartrate]])

        Heart_Disease = result[0]

        PredResults.objects.create(Patient_ID=Patient_ID, Patient_Age=Patient_Age, Patient_Gender=Patient_Gender,
                                   Patient_Blood_Pressure=Patient_Blood_Pressure, Patient_Heartrate=Patient_Heartrate, Heart_Disease=Heart_Disease)

        return JsonResponse({'result': Heart_Disease, 'Patient_ID': Patient_ID,
                             'Patient_Age': Patient_Age, 'Patient_Gender': Patient_Gender, 'Patient_Blood_Pressure': Patient_Blood_Pressure, 'Patient_Heartrate': Patient_Heartrate},
                            safe=False)


def view_results(request):
    # Submit prediction and show all
    data = {"dataset": PredResults.objects.all()}
    return render(request, "results.html", data)

def view_about(request):
    return render(request, 'about.html')


def view_doctor(request):
    return render(request, 'doctor.html')

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("predict:prediction_page")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm
	return render (request=request, template_name="register.html", context={"register_form":form})

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("predict:prediction_page")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="login.html", context={"login_form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.")
	return render(request,"home.html")

templates/about.html
{% extends "base.html" %}
{% block main %}

<h1>about Us</h1>
<p>Our project is Heart Monitoring and Care System. Heart or Cardiovascular disease is one of the fatal disease in the world, but it can be controlled by utilization of the previous medical records of the patients. With the help of machine learning we can predict the chances of Heart Diseases amongst people.

In this we use attributes such as age, blood pressure, heart rate etc and fed them into the algorithms to predict the risk of heart disease in people with the help of Machine Learning.</p>

<p>Heart Monitoring and Care System is a Machine learning project integrated with Django framework. In this system user will input attributes such as age , blood pressure and heart rate and by using these attributes the system can predict if the person has any heart disease or not by using Large data set. The system will also contain Medical help modules for the user. This system will be beneficial for people to detect heart disease chances at the earliest.</p>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- new -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- end new -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="styles.css">

    <title>Heart Disease Prediction</title>
    <style>
   body{
  background-image: url('https://i.pinimg.com/originals/7f/15/4c/7f154ce9a822d6532b1283856e5439cf.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}
#Col{
  background:#f75736;
  color:white;
  border-radius:4px;
  text-align:center;
 display:inline-block;
}
#Co{
  background:#38b070;
  color:white;
  border-radius:4px;
  text-align:center;
 display:inline-block;
}
/* hover */
img:hover {
  animation: shake 0.5s;
  animation-iteration-count: infinite;
}
#Co:hover{
  animation: shake 0.5s;
  animation-iteration-count: infinite;
}

@keyframes shake {
  0% { transform: translate(1px, 1px) rotate(0deg); }
  10% { transform: translate(-1px, -2px) rotate(-1deg); }
  20% { transform: translate(-3px, 0px) rotate(1deg); }
  30% { transform: translate(3px, 2px) rotate(0deg); }
  40% { transform: translate(1px, -1px) rotate(1deg); }
  50% { transform: translate(-1px, 2px) rotate(-1deg); }
  60% { transform: translate(-3px, 1px) rotate(0deg); }
  70% { transform: translate(3px, 1px) rotate(-1deg); }
  80% { transform: translate(-1px, -1px) rotate(1deg); }
  90% { transform: translate(1px, 2px) rotate(0deg); }
  100% { transform: translate(1px, -2px) rotate(-1deg); }
}
.footer-dark {
  padding:50px 0;
  color:#f0f9ff;
  background-color:#282d32;
}

.footer-dark h3 {
  margin-top:0;
  margin-bottom:12px;
  font-weight:bold;
  font-size:16px;
}

.footer-dark ul {
  padding:0;
  list-style:none;
  line-height:1.6;
  font-size:14px;
  margin-bottom:0;
}

.footer-dark ul a {
  color:inherit;
  text-decoration:none;
  opacity:0.6;
}

.footer-dark ul a:hover {
  opacity:0.8;
}

@media (max-width:767px) {
  .footer-dark .item:not(.social) {
    text-align:center;
    padding-bottom:20px;
  }
}

.footer-dark .item.text {
  margin-bottom:36px;
}

@media (max-width:767px) {
  .footer-dark .item.text {
    margin-bottom:0;
  }
}

.footer-dark .item.text p {
  opacity:0.6;
  margin-bottom:0;
}

.footer-dark .item.social {
  text-align:center;
}

@media (max-width:991px) {
  .footer-dark .item.social {
    text-align:center;
    margin-top:20px;
  }
}

.footer-dark .item.social > a {
  font-size:20px;
  width:36px;
  height:36px;
  line-height:36px;
  display:inline-block;
  text-align:center;
  border-radius:50%;
  box-shadow:0 0 0 1px rgba(255,255,255,0.4);
  margin:0 8px;
  color:#fff;
  opacity:0.75;
}

.footer-dark .item.social > a:hover {
  opacity:0.9;
}

.footer-dark .copyright {
  text-align:center;
  padding-top:24px;
  opacity:0.3;
  font-size:13px;
  margin-bottom:0;
}

</style>
</head>
<body>
</style>
    </head>
    <body>



      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <img src="https://cdn.iconscout.com/icon/free/png-256/health-fitness-care-safe-fresh-heart-1-4142.png" height="35" width="30" alt="">
          &nbsp;
          <a id="Col" class="navbar-brand" href="/predictor">&nbsp;HD-Predictor&nbsp;</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/about">About us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/doctor">Doctor's Profile</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" href="/results">DataBase</a>
              </li>
              <li class="nav-item dropdown">
       <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         COVID-19 Resources
       </a>
       <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
         <a class="dropdown-item" href="#" onclick='window.open("https://www.who.int/news");return false;'>News</a>
         <a class="dropdown-item" href="#" onclick='window.open("https://www.who.int/health-topics/coronavirus#tab=tab_1");return false;'>Symptoms</a>
         <a class="dropdown-item" href="#" onclick='window.open("https://www.who.int/publications/i/item/WHO-2019-nCoV-clinical-2021-1");return false;'>Treatment</a>
       </div>
     </li>


              </ul><ul></ul><ul></ul><ul>              </ul><ul></ul><ul></ul><ul>
              </ul><ul></ul><ul></ul><ul>              </ul><ul>



              </ul><ul></ul>&nbsp;&nbsp;&nbsp;&nbsp;
              <ul class="navbar-nav  " style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/register">SignUp</a>
                </li>

                </ul>
                <div class="collapse navbar-collapse" id="navbarText">
                  <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link active" href="/logout">Logout</a>
                    </li>

                    <li class="nav-item">
                                  <a id="Co" class="nav-link" href="#">Welcome, {{user.username}} </a>
                                </li>

                    {% else %}

                    <li class="nav-item">
                      <a class="nav-link active" href="/login">Login</a>
                    </li>

                    {% endif %}
                  </ul>
                </div>
          </div>
        </div>
      </nav>


    {% block main %}
    {% endblock %}
    <br>
<!-- footer -->
<div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Web design</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Hosting</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Heart Care Monitoring and Care System</h3>
                        <p>Heart Monitoring and Care System is a Machine learning project integrated with Django framework. In this system user will input attributes such as age , blood pressure and heart rate and by using these attributes the system can predict if the person has any heart disease or not by using Large data set. The system will also contain Medical help modules for the user. This system will be beneficial for people to detect heart disease chances at the earliest.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">Heart Care Monitoring and Care System © 2021</p>
            </div>
        </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </body>
</html>

templates/doctor.html
{% extends "base.html" %}
{% block main %}

<h1>Doctors Profile</h1>
<p>Our project is Heart Monitoring and Care System. Heart or Cardiovascular disease is one of the fatal disease in the world, but it can be controlled by utilization of the previous medical records of the patients. With the help of machine learning we can predict the chances of Heart Diseases amongst people.

In this we use attributes such as age, blood pressure, heart rate etc and fed them into the algorithms to predict the risk of heart disease in people with the help of Machine Learning.</p>

<p>Heart Monitoring and Care System is a Machine learning project integrated with Django framework. In this system user will input attributes such as age , blood pressure and heart rate and by using these attributes the system can predict if the person has any heart disease or not by using Large data set. The system will also contain Medical help modules for the user. This system will be beneficial for people to detect heart disease chances at the earliest.</p>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

templates/login.html
<!doctype html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="styles.css">

    <title>Heart Disease Prediction</title>
    <style>
   body{
  background-image: url('https://i.pinimg.com/originals/7f/15/4c/7f154ce9a822d6532b1283856e5439cf.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}
</style>
    </head>
    <body>



      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <img src="https://cdn.iconscout.com/icon/free/png-256/health-fitness-care-safe-fresh-heart-1-4142.png" height="35" width="30" alt="">
          &nbsp;
          <a class="navbar-brand" href="#">HD-Predictor</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>



              </ul><ul></ul><ul></ul><ul>              </ul><ul></ul><ul></ul><ul>
              </ul><ul></ul><ul></ul><ul>              </ul><ul></ul><ul></ul><ul>
              </ul><ul></ul><ul></ul><ul>              </ul><ul></ul><ul></ul><ul>
              </ul><ul></ul><ul></ul><ul>              </ul><ul></ul><ul></ul><ul>
              </ul><ul></ul><ul></ul><ul>              </ul><ul></ul><ul></ul><ul>






              </ul>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <ul class="navbar-nav  " style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/register">SignUp</a>
                </li>

                </ul>
                <div class="collapse navbar-collapse" id="navbarText">
                  <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}

                    {% else %}

                    <li class="nav-item">
                      <a class="nav-link active" href="/login">Login</a>
                    </li>

                    {% endif %}
                  </ul>
                </div>
          </div>
        </div>
      </nav>

      {% load crispy_forms_tags %}
      <div class="p-4 m-4">
       <div class="col-lg-5 mx-auto border rounded border-dark border-5 pt-4">

      <div class="container py-5">
        <h1 style="text-align:center">Login</h1>
        <form method="POST">
          {% csrf_token %}
          {{ login_form|crispy }}
          <button class="btn btn-primary" type="submit">Login</button>
        </form>
        <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
      </div>
      </div>
      </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </body>
</html>

templates/predict.html
{% extends "base.html" %}

{% block main %}
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>Patient ID: <span id="sl"></span></div>
                <div>Patient Age: <span id="sw"></span></div>
                <div>Patient Gender: <span id="pl"></span></div>
                <div>Patient Blood Pressure: <span id="pw"></span></div>
                <div>Patient Heartrate: <span id="pn"></span></div>
                <h5 class="pt-3">Disease Prediction:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>
<style>
h1 {text-align: center;}

</style>
<div class="container pt-5">
  <h1>Heart Disease Prediction System</h1>
    <div class="row justify-content-md-center">

        <div class="col-md-4">

            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="Patient_ID">Enter Patient ID</label>
                    <input type="number" step="1" class="form-control" id="Patient_ID" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="Patient_Age">Enter Patient Age</label>
                    <input type="number" step="1" class="form-control" id="Patient_Age" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="Patient_Gender">Enter Patient Gender  (0 for Female & 1 for Male)</label>
                    <input type="number" step="1" class="form-control" id="Patient_Gender" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="Patient_Blood_Pressure">Enter Patient Blood Pressure</label>
                    <input type="number" step="1" class="form-control" id="Patient_Blood_Pressure" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="Patient_Heartrate">Enter Patient Heartrate</label>
                    <input type="number" step="1" class="form-control" id="Patient_Heartrate" placeholder="" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                Patient_ID:$('#Patient_ID').val(),
                Patient_Age:$('#Patient_Age').val(),
                Patient_Gender:$('#Patient_Gender').val(),
                Patient_Blood_Pressure:$('#Patient_Blood_Pressure').val(),
                Patient_Heartrate:$('#Patient_Heartrate').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("sl").innerHTML = json['Patient_ID']
                document.getElementById("sw").innerHTML = json['Patient_Age']
                document.getElementById("pl").innerHTML = json['Patient_Gender']
                document.getElementById("pw").innerHTML = json['Patient_Blood_Pressure']
                document.getElementById("pn").innerHTML = json['Patient_Heartrate']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

templates/results.html
{% extends "base.html" %}

{% block main %}
    <div style="background-image: url('https://cutewallpaper.org/21/grey-background-hd/Winning-Light-Gray-Background-Grey-Plain-Css-Color-Images-.jpg');">
    <div class="container pt-5">
        <div class="row">

        <h1>Prediction Results</h1>

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Patient ID</th>
                    <th scope="col">Patient Age</th>
                    <th scope="col">Patient Gender</th>
                    <th scope="col">Patient Blood Pressure</th>
                    <th scope="col">Patient Heartrate</th>
                    <th scope="col">Prediction</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                        <td>{{ data.Patient_ID }}</td>
                        <td>{{ data.Patient_Age }}</td>
                        <td>{{ data.Patient_Gender }}</td>
                        <td>{{ data.Patient_Blood_Pressure }}</td>
                        <td>{{ data.Patient_Heartrate }}</td>
                        <td>{{ data.Heart_Disease }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}